apiVersion: v1
kind: Secret
metadata:
  name: bh-core-secret
type: Opaque
stringData:
  # En producción, esto no se debe guardar en texto plano en el repositorio
  DB_PASSWORD: "postgres_password"
  JWT_SECRET: "super_secret_jwt_key_for_bh_core_2026"
