export enum AuditAction {
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',

    CREAR_USUARIO = 'CREAR_USUARIO',
    APROBAR_USUARIO = 'APROBAR_USUARIO',
    RECHAZAR_USUARIO = 'RECHAZAR_USUARIO',
    SUSPENDER_USUARIO = 'SUSPENDER_USUARIO',

    CREAR_MASCOTA = 'CREAR_MASCOTA',
    ACTUALIZAR_MASCOTA = 'ACTUALIZAR_MASCOTA',

    CREAR_CITA = 'CREAR_CITA',
    COMPLETAR_CITA = 'COMPLETAR_CITA',
    CANCELAR_CITA = 'CANCELAR_CITA',

    CREAR_SERVICIO = 'CREAR_SERVICIO',
    ACTUALIZAR_SERVICIO = 'ACTUALIZAR_SERVICIO',

    CREAR_INVENTARIO = 'CREAR_INVENTARIO',
    AJUSTAR_INVENTARIO = 'AJUSTAR_INVENTARIO',

    HOSPITALIZAR_MASCOTA = 'HOSPITALIZAR_MASCOTA',
    MARCAR_FALLECIMIENTO = 'MARCAR_FALLECIMIENTO',
}