export enum AuditAction {
    // Auth
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    REGISTRO_USUARIO = 'REGISTRO_USUARIO',
    VERIFICACION_CORREO = 'VERIFICACION_CORREO',
    REENVIO_CODIGO_VERIFICACION = 'REENVIO_CODIGO_VERIFICACION',
    LOGIN_EXITOSO = 'LOGIN_EXITOSO',
    LOGIN_FALLIDO = 'LOGIN_FALLIDO',

    // Usuarios
    APROBACION_CUENTA = 'APROBACION_CUENTA',
    RECHAZO_CUENTA = 'RECHAZO_CUENTA',
    SUSPENSION_USUARIO = 'SUSPENSION_USUARIO',

    // Mascotas
    CREACION_MASCOTA = 'CREACION_MASCOTA',
    ACTUALIZACION_MASCOTA = 'ACTUALIZACION_MASCOTA',
    HOSPITALIZACION_MASCOTA = 'HOSPITALIZACION_MASCOTA',
    FALLECIMIENTO_MASCOTA = 'FALLECIMIENTO_MASCOTA',

    // Citas
    CREACION_CITA = 'CREACION_CITA',
    CAMBIO_ESTADO_CITA = 'CAMBIO_ESTADO_CITA',
    FINALIZACION_CITA = 'FINALIZACION_CITA',
    CANCELACION_CITA = 'CANCELACION_CITA',
    PAGO_CITA_REGISTRADO = 'PAGO_CITA_REGISTRADO',

    // Servicios
    CREACION_SERVICIO = 'CREACION_SERVICIO',
    EDICION_SERVICIO = 'EDICION_SERVICIO',
    ACTUALIZACION_PRECIO_SERVICIO = 'ACTUALIZACION_PRECIO_SERVICIO',
    DESACTIVACION_SERVICIO = 'DESACTIVACION_SERVICIO',
    ACTIVACION_SERVICIO = 'ACTIVACION_SERVICIO',

    // Inventario
    CREACION_INVENTARIO = 'CREACION_INVENTARIO',
    AJUSTE_INVENTARIO = 'AJUSTE_INVENTARIO',
    DEDUCCION_STOCK_PRESCRIPCION = 'DEDUCCION_STOCK_PRESCRIPCION',
    ACTUALIZACION_INVENTARIO = 'ACTUALIZACION_INVENTARIO',

    // Facturación
    CREACION_FACTURA = 'CREACION_FACTURA',
    ANULACION_FACTURA = 'ANULACION_FACTURA',

    // Historial médico
    CREACION_HISTORIAL_MEDICO = 'CREACION_HISTORIAL_MEDICO',
    EDICION_HISTORIAL_MEDICO = 'EDICION_HISTORIAL_MEDICO',
    REGISTRO_VACUNA = 'REGISTRO_VACUNA',

    // Hospitalización
    INICIO_HOSPITALIZACION = 'INICIO_HOSPITALIZACION',
    ALTA_HOSPITALIZACION = 'ALTA_HOSPITALIZACION',

    // Clientes
    REGISTRO_CLIENTE = 'REGISTRO_CLIENTE',
    ACTUALIZACION_CLIENTE = 'ACTUALIZACION_CLIENTE',
}
