export enum AuditAction {
    // Auth
    LOGIN = 'LOGIN',
    LOGOUT = 'LOGOUT',
    REGISTRO_DE_USUARIO = 'REGISTRO_DE_USUARIO',
    VERIFICACION_CORREO = 'VERIFICACION_CORREO',
    REENVIO_CODIGO_VERIFICACION = 'REENVIO_CODIGO_VERIFICACION',
    INICIO_DE_SESION_EXITOSO = 'INICIO_DE_SESION_EXITOSO',
    INTENTO_DE_SESION_FALLIDO = 'INTENTO_DE_SESION_FALLIDO',

    // Usuarios
    APROBACION_DE_CUENTA = 'APROBACION_DE_CUENTA',
    RECHAZO_DE_CUENTA = 'RECHAZO_DE_CUENTA',
    SUSPENSION_DE_USUARIO = 'SUSPENSION_DE_USUARIO',

    // Mascotas
    CREACION_MASCOTA = 'CREACION_MASCOTA',
    ACTUALIZACION_MASCOTA = 'ACTUALIZACION_MASCOTA',
    HOSPITALIZACION_MASCOTA = 'HOSPITALIZACION_MASCOTA',
    FALLECIMIENTO_MASCOTA = 'FALLECIMIENTO_MASCOTA',

    // Citas
    CREACION_CITA = 'CREACION_CITA',
    FINALIZACION_CITA = 'FINALIZACION_CITA',
    CANCELACION_CITA = 'CANCELACION_CITA',
    PAGO_CITA_REGISTRADO = 'PAGO_CITA_REGISTRADO',

    // Servicios
    CREACION_SERVICIO = 'CREACION_SERVICIO',
    EDICION_SERVICIO = 'EDICION_SERVICIO',
    DESACTIVACION_SERVICIO = 'DESACTIVACION_SERVICIO',

    // Inventario
    CREACION_INVENTARIO = 'CREACION_INVENTARIO',
    AJUSTE_INVENTARIO = 'AJUSTE_INVENTARIO',

    // Historial médico
    CREACION_HISTORIAL_MEDICO = 'CREACION_HISTORIAL_MEDICO',
}